//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_store
    {
        public int Id { get; set; }
        public string Name_of_the_drug { get; set; }
        public decimal Price { get; set; }
        public Nullable<short> quantity { get; set; }
        public System.DateTime production_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public string Factory { get; set; }
    }
}
